### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by MarkKazakov** [swift-server/webauthn-swift#30]
Having the following errors on compilation:

`
The package product 'Crypto' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0. 
The package product 'X509' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0. 
The package product '_CryptoExtras' requires minimum platform version 13.0 for the iOS platform, but this target supports 12.0
`

Same issues occur on a new empty projects with deployment target set to iOS 15.

**Comment by 0xTim** [comment]
If this is for an iOS project (which I'd be very interested to know the use case because it's aimed at the server!) you need to set your minimum target version to iOS 13. This is **not** the same as the deployment target

**Comment by MarkKazakov** [comment]
@0xTim , thanks a lot for your reply.
I thought this lib was a clientside part of webauthn implementation, so I wanted to test it out.
Thanks for clarifying.

**Comment by marius-se** [comment]
@MarkKazakov for that you'll need the built-in [AuthenticationServices](https://developer.apple.com/documentation/authenticationservices) framework. How to implement Passkeys client-side on iOS: https://developer.apple.com/documentation/authenticationservices/public-private_key_authentication/supporting_passkeys
