### ISSUE TITLE
Add CI step to catch breaking API changes

### ISSUE THREAD

**Issue by dimitribouniol** [swift-server/webauthn-swift#50]
It's probably worthwhile adding in CI to catch breaking changes at this stage. Not sure how CI is setup for this repo though.

_Originally posted by @adam-fowler in https://github.com/swift-server/webauthn-swift/issues/43#issuecomment-1952632887_

**Comment by 0xTim** [comment]
@dimitribouniol If you're up for it see https://github.com/swift-server/async-http-client/blob/main/scripts/check_no_api_breakages.sh as an example (and also the docker compose file)

**Comment by dimitribouniol** [comment]
I can take a look later today after I rebase the last of the PRs!
