### ISSUE TITLE
Fix or eliminate ChallengeGenerator

### ISSUE THREAD

**Issue by Jerry-Carter** [swift-server/webauthn-swift#62]
The ChallengeGenerator in 0.0.3 version allows the API user to replace the function which generates the challenge bytes. At present, this structure cannot be extended as no public initializer exists. To fix, just add a public initializer.

Alternatively, the structure can be eliminated entirely by allowing the API user to optionally pass in challenge bytes to the WebAuthnManager `beginRegistration` and `beginAuthentication functions`. If a byte array of the correct length is passed in, these are used; otherwise, the code just calls `[UInt8].random(count: 32)` as provided in the default implementation of ChallengeGenerator.

Fixing ChallengeGenerator is the easy fix, but eliminating it feels like a cleaner API since this is the only place where random numbers appear to be generated.

**Comment by Jerry-Carter** [comment]
[Apologies, somehow accidentally submitted before writing the description.]

The ChallengeGenerator in 0.0.3 version allows the API user to replace the function which generates the challenge bytes.  At present, this structure cannot be extended as no public initializer exists.  To fix, just add a public initializer.

Alternatively, the structure can be eliminated entirely by allowing the API user to optionally pass in challenge bytes to the WebAuthnManager `beginRegistration` and `beginAuthentication` functions.  If a byte array of the correct length is passed in, these are used; otherwise, the code just calls `[UInt8].random(count: 32)` as provided in the default implementation of ChallengeGenerator.

Fixing ChallengeGenerator is the easy fix, but eliminating it feels like a cleaner API since this is the only place were random numbers appear to be generated.

**Comment by 0xTim** [comment]
This was probably exposed to allow for testing, but we can use the new package visibility stuff instead to fix this and remove it from the API
