### ISSUE TITLE
Roadmap to releasable/stable version?

### ISSUE THREAD

**Issue by Joride** [swift-server/webauthn-swift#77]
As noted by Dimitri Bouniol [here](https://github.com/swift-server/webauthn-swift/pull/76#discussion_r1721945549), this package is currently in pre-release.
I'm planning to start using this package in a production environment before the end of the year. While I'm ok to deal with breaking changes and adjust my project as necessary of course, I would gladly start actively supporting this repo if needed and get this package to production-ready asap.

Any hints/thoughts on this?

**Comment by 0xTim** [comment]
It's pretty much there. There are a couple of PRs that contain some small breaking changes and then making sure the API works across all the different use cases. That's the most beneficial contribution at the moment! But I'm hoping we should have a 1.0 around the Swift 6 time

**Comment by Joride** [comment]
Great to hear! Just for my clarity :), the PRs that you mentioned, would that be inclusive of this one [Expanded PublicKeyCredentialCreationOptions #76](https://github.com/swift-server/webauthn-swift/pull/76)?

Is there a list of use cases somewhere to keep track of how close we are getting?

**Comment by 0xTim** [comment]
Yeah I need to go through them and see if they make sense but yes that PR is included and at an initial glance looks good.

In terms of use cases no I don't have anything. The WebAuthn spec is pretty wide so it's just if people use it for whatever thing they have and if we need to support it but currently don't. (FWIW I think we cover the spec pretty well and I'm not expecting anything to come up but open source always surprises you)
